spring.application.name=Muttley

spring.datasource.url=jdbc:mysql://localhost:3306/db_muttley?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=false
spring.mvc.hiddenmethod.filter.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.thymeleaf.cache=false


server.port=8083


