spring.application.name=Muttley-API

# Conexão com o banco usando Variáveis de Ambiente e Valores Padrão (Fallback)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/db_muttley?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:alunofatec}

# O resto continua igual
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8083

# --- CONFIGURAÇÃO DE E-MAIL (GMAIL) ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=muttley834@gmail.com
spring.mail.password=cumz uoad hcor rveu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# --- CONFIGURAÇÃO DE USUÁRIO ADMIN ---
muttley.admin.default-user=admin@fatec.sp.gov.br
muttley.admin.default-password=fateczl123
muttley.cors.origins=http://localhost:3000